### PR TITLE
Pylint cleanup to make it pass nicer

### PR DESCRIPTION
**Pull request by Vermyndax**

### CODE REVIEW

**Comment by Vermyndax** [comment]
Ready for merging

**Review by briankfitzwater — APPROVED** [review]
Now you just need to add your CircleCI badge of honor to the README

**Comment by afeld** [comment]
Did you mean to commit the ZIP file?

**Comment by Vermyndax** [comment]
@afeld yes, unfortunately the terraform lambda object requires a zip file to upload. It won’t take a raw python file.

**Comment by afeld** [comment]
Right - I just mean that the ZIP file is an artifact, and therefore should probably be `gitignore`d.

**Comment by Vermyndax** [comment]
In that event, a person using this repo will have to manually zip it prior to deployment. I didn’t see the need to add that manual step.

**Pull request merged**
