### PR TITLE
Initial working implementation

### PR DESCRIPTION
**Pull request by Vermyndax**

### CODE REVIEW

**Comment by briankfitzwater** [comment]
- CircleCI configuration running `terraform validate` and `pylint` would be nice.

**Comment by briankfitzwater** [comment]
pylint found the following:

```
************* Module lambda_ebs_backup
C: 21, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 57, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C: 63, 0: Final newline missing (missing-final-newline)
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Constant name "ec" doesn't conform to UPPER_CASE naming style (invalid-name)
C:  7, 0: Missing function docstring (missing-docstring)
W:  7,26: Unused argument 'context' (unused-argument)
W:  7,19: Unused argument 'event' (unused-argument)
C:  2, 0: standard import "import collections" should be placed before "import boto3" (wrong-import-order)
C:  3, 0: standard import "import datetime" should be placed before "import boto3" (wrong-import-order)
************* Module lambda_ebs_backup_cleaner
C: 40, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Constant name "ec" doesn't conform to UPPER_CASE naming style (invalid-name)
C:  6, 0: Constant name "iam" doesn't conform to UPPER_CASE naming style (invalid-name)
C: 15, 0: Missing function docstring (missing-docstring)
W: 26,11: Catching too general exception Exception (broad-except)
W: 24,-1: String statement has no effect (pointless-string-statement)
C: 26,24: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
W: 15,26: Unused argument 'context' (unused-argument)
W: 15,19: Unused argument 'event' (unused-argument)
C:  2, 0: standard import "import re" should be placed before "import boto3" (wrong-import-order)
C:  3, 0: standard import "import datetime" should be placed before "import boto3" (wrong-import-order)

-----------------------------------
Your code has been rated at 5.22/10
```

**Comment by Vermyndax** [comment]
Run it against python 3.6, not 2.7.

**Comment by Vermyndax** [comment]
Agree on CircleCI. I will make another pass on that in another branch, though.

**Review by briankfitzwater — APPROVED** [review]
I'll have to take your word on the python3 lint results; mine Python3 install is hopelessly broken.  Looking forward to CircleCI doing the lint check.

**Pull request merged**
